name: Kaggle Notebook Trigger

on:
  push:
    paths:
      - 'data/intent'
      - 'data/entity'
      - 'data/reranker'

jobs:
  trigger_notebooks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.10.6

      - name: Install Kaggle CLI
        run: pip install kaggle

      - name: Configure Kaggle
        run: |
          kaggle config set -n username -v ${{ secrets.KAGGLE_USERNAME }}
          kaggle config set -n key -v ${{ secrets.KAGGLE_KEY }}

      - name: Trigger Intent Notebook
        if: ${{ contains(github.event_paths, 'data/intent') }}
        run: kaggle kernels push -p intent

      - name: Trigger Entity Notebook
        if: ${{ contains(github.event_paths, 'data/entity') }}
        run: kaggle kernels push -p entity
      - name: Trigger Reranker Notebook
        if: ${{ contains(github.event_paths, 'data/reranker') }}
        run: kaggle kernels push -p reranker